<a href="https://colab.research.google.com/github/tarundb2005-create/Ml-linear-regression/blob/main/LinearRegression_Multivariate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
#adding meadian to the null value
#data preprocess
import math

median_bedroom = math.floor(df.bedrooms.median())
median_bedroom

4

In [19]:
#fill NaN
df.bedrooms = df.bedrooms.fillna(median_bedroom)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
reg = linear_model.LinearRegression()
reg

LinearRegression()

In [20]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [22]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([498408.25158031])

In [23]:
#checking by manual
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [24]:
reg.intercept_

np.float64(221323.00186540396)

In [26]:
pred = 112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540396
pred

498408.251574024